import type { Metadata } from "next";
import { Noto_Sans, Anton } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers/provider";
import Navbar from "@/components/layout/Navbar";
import { ViewTransitions } from "next-view-transitions";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto",
});

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${notoSans.variable} ${anton.variable} antialiased`}
        >
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </html>
    </ViewTransitions>
  );
}
